"""Built-in timer levels from the Focus Timer Levels system (76.2% focus ratio)."""

BUILTINS = [
    {
        "id": "builtin-navin",
        "name": "Navin",
        "subtitle": "Starter",
        "work_min": 12,
        "short_rest_min": 3,
        "long_rest_min": 6,
        "total_work_min": 48,
        "total_rest_min": 15,
        "cycle_min": 63,
        "muhurat_note": "1 Muhurat focus · 5/8 Ghadi rest",
    },
    {
        "id": "builtin-shishya",
        "name": "Shishya",
        "subtitle": "Beginner",
        "work_min": 24,
        "short_rest_min": 6,
        "long_rest_min": 12,
        "total_work_min": 96,
        "total_rest_min": 30,
        "cycle_min": 126,
        "muhurat_note": "2 Muhurat focus · 1¼ Ghadi rest",
    },
    {
        "id": "builtin-sadhaka",
        "name": "Sadhaka",
        "subtitle": "Intermediate",
        "work_min": 36,
        "short_rest_min": 9,
        "long_rest_min": 18,
        "total_work_min": 144,
        "total_rest_min": 45,
        "cycle_min": 189,
        "muhurat_note": "3 Muhurat focus · 1⅞ Ghadi rest",
    },
    {
        "id": "builtin-abhyasi",
        "name": "Abhyasi",
        "subtitle": "Regular",
        "work_min": 48,
        "short_rest_min": 12,
        "long_rest_min": 24,
        "total_work_min": 192,
        "total_rest_min": 60,
        "cycle_min": 252,
        "muhurat_note": "4 Muhurat focus · 2½ Ghadi rest",
    },
    {
        "id": "builtin-madhyami",
        "name": "Madhyami",
        "subtitle": "Focused",
        "work_min": 60,
        "short_rest_min": 15,
        "long_rest_min": 30,
        "total_work_min": 240,
        "total_rest_min": 75,
        "cycle_min": 315,
        "muhurat_note": "5 Muhurat focus · 3⅛ Ghadi rest",
    },
    {
        "id": "builtin-dhyani",
        "name": "Dhyani",
        "subtitle": "Advanced",
        "work_min": 72,
        "short_rest_min": 18,
        "long_rest_min": 36,
        "total_work_min": 288,
        "total_rest_min": 90,
        "cycle_min": 378,
        "muhurat_note": "6 Muhurat focus · 3¾ Ghadi rest",
    },
    {
        "id": "builtin-nishtha",
        "name": "Nishtha",
        "subtitle": "Dedicated",
        "work_min": 84,
        "short_rest_min": 21,
        "long_rest_min": 42,
        "total_work_min": 336,
        "total_rest_min": 105,
        "cycle_min": 441,
        "muhurat_note": "7 Muhurat focus · 4⅜ Ghadi rest",
    },
    {
        "id": "builtin-ekagra",
        "name": "Ekagra",
        "subtitle": "Flow",
        "work_min": 96,
        "short_rest_min": 24,
        "long_rest_min": 48,
        "total_work_min": 384,
        "total_rest_min": 120,
        "cycle_min": 504,
        "muhurat_note": "8 Muhurat focus · 5 Ghadi rest",
    },
]
