"""Built-in timer levels from the Focus Timer Levels system (76.2% focus ratio)."""

BUILTINS = [
    {
        "id": "builtin-navin",
        "name": "Agaman",
        "subtitle": "Arriving",
        "work_min": 12,
        "short_rest_min": 3,
        "long_rest_min": 6,
        "work_cycles": 4,
        "total_work_min": 48,
        "total_rest_min": 15,
        "cycle_min": 63,
        "muhurat_note": "1 Muhurat focus · 5/8 Ghadi rest",
    },
    {
        "id": "builtin-shishya",
        "name": "Sparsha",
        "subtitle": "First Touch",
        "work_min": 24,
        "short_rest_min": 6,
        "long_rest_min": 12,
        "work_cycles": 4,
        "total_work_min": 96,
        "total_rest_min": 30,
        "cycle_min": 126,
        "muhurat_note": "2 Muhurat focus · 1¼ Ghadi rest",
    },
    {
        "id": "builtin-sadhaka",
        "name": "Sthiti",
        "subtitle": "Steadiness",
        "work_min": 36,
        "short_rest_min": 9,
        "long_rest_min": 18,
        "work_cycles": 4,
        "total_work_min": 144,
        "total_rest_min": 45,
        "cycle_min": 189,
        "muhurat_note": "3 Muhurat focus · 1⅞ Ghadi rest",
    },
    {
        "id": "builtin-abhyasi",
        "name": "Abhyasi",
        "subtitle": "Established",
        "work_min": 48,
        "short_rest_min": 12,
        "long_rest_min": 24,
        "work_cycles": 4,
        "total_work_min": 192,
        "total_rest_min": 60,
        "cycle_min": 252,
        "muhurat_note": "4 Muhurat focus · 2½ Ghadi rest",
    },
    {
        "id": "builtin-madhyami",
        "name": "Tapas",
        "subtitle": "The Fire",
        "work_min": 60,
        "short_rest_min": 15,
        "long_rest_min": 30,
        "work_cycles": 4,
        "total_work_min": 240,
        "total_rest_min": 75,
        "cycle_min": 315,
        "muhurat_note": "5 Muhurat focus · 3⅛ Ghadi rest",
    },
    {
        "id": "builtin-dhyani",
        "name": "Samadhan",
        "subtitle": "Resolution",
        "work_min": 72,
        "short_rest_min": 18,
        "long_rest_min": 36,
        "work_cycles": 4,
        "total_work_min": 288,
        "total_rest_min": 90,
        "cycle_min": 378,
        "muhurat_note": "6 Muhurat focus · 3¾ Ghadi rest",
    },
    {
        "id": "builtin-nishtha",
        "name": "Tanmaya",
        "subtitle": "Becoming It",
        "work_min": 84,
        "short_rest_min": 21,
        "long_rest_min": 42,
        "work_cycles": 4,
        "total_work_min": 336,
        "total_rest_min": 105,
        "cycle_min": 441,
        "muhurat_note": "7 Muhurat focus · 4⅜ Ghadi rest",
    },
    {
        "id": "builtin-ekagra",
        "name": "Ekagra",
        "subtitle": "One-Pointed",
        "work_min": 96,
        "short_rest_min": 24,
        "long_rest_min": 48,
        "work_cycles": 4,
        "total_work_min": 384,
        "total_rest_min": 120,
        "cycle_min": 504,
        "muhurat_note": "8 Muhurat focus · 5 Ghadi rest",
    },
]
