// Fallback quotes for Muhurat · Focus timer
// 150 curated quotes: focus, wisdom, discipline, growth, philosophy
// Usage: const q = FALLBACK_QUOTES[Math.floor(Math.random() * FALLBACK_QUOTES.length)];

const FALLBACK_QUOTES = [
  { q: "The successful warrior is the average man, with laser-like focus.", a: "Bruce Lee" },
  { q: "It is not enough to be busy. The question is: what are we busy about?", a: "Henry David Thoreau" },
  { q: "You have power over your mind, not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius" },
  { q: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", a: "Alexander Graham Bell" },
  { q: "The difference between successful people and really successful people is that really successful people say no to almost everything.", a: "Warren Buffett" },
  { q: "Until we can manage time, we can manage nothing else.", a: "Peter Drucker" },
  { q: "Lost time is never found again.", a: "Benjamin Franklin" },
  { q: "He who is not courageous enough to take risks will accomplish nothing in life.", a: "Muhammad Ali" },
  { q: "The mind is not a vessel to be filled, but a fire to be kindled.", a: "Plutarch" },
  { q: "Do not wait; the time will never be 'just right.' Start where you stand.", a: "Napoleon Hill" },
  { q: "What you do today can improve all your tomorrows.", a: "Ralph Marston" },
  { q: "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.", a: "Zig Ziglar" },
  { q: "The secret of getting ahead is getting started.", a: "Mark Twain" },
  { q: "Action is the foundational key to all success.", a: "Pablo Picasso" },
  { q: "If you spend too much time thinking about a thing, you'll never get it done.", a: "Bruce Lee" },
  { q: "You don't have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
  { q: "Nothing will work unless you do.", a: "Maya Angelou" },
  { q: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", a: "Stephen King" },
  { q: "Discipline is choosing between what you want now and what you want most.", a: "Abraham Lincoln" },
  { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Aristotle" },
  { q: "The true price of leadership is the willingness to place the needs of others above your own.", a: "Simon Sinek" },
  { q: "It always seems impossible until it's done.", a: "Nelson Mandela" },
  { q: "Perfection is not attainable, but if we chase perfection we can catch excellence.", a: "Vince Lombardi" },
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { q: "In the middle of every difficulty lies opportunity.", a: "Albert Einstein" },
  { q: "I am not a product of my circumstances. I am a product of my decisions.", a: "Stephen Covey" },
  { q: "The man who moves a mountain begins by carrying away small stones.", a: "Confucius" },
  { q: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe" },
  { q: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius" },
  { q: "Our greatest glory is not in never failing, but in rising every time we fall.", a: "Confucius" },
  { q: "Waste no more time arguing what a good man should be. Be one.", a: "Marcus Aurelius" },
  { q: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", a: "Marcus Aurelius" },
  { q: "The impediment to action advances action. What stands in the way becomes the way.", a: "Marcus Aurelius" },
  { q: "If it is not right, do not do it; if it is not true, do not say it.", a: "Marcus Aurelius" },
  { q: "Begin at once to live, and count each separate day as a separate life.", a: "Seneca" },
  { q: "It is not that we have a short time to live, but that we waste a good deal of it.", a: "Seneca" },
  { q: "Luck is what happens when preparation meets opportunity.", a: "Seneca" },
  { q: "While we are postponing, life speeds by.", a: "Seneca" },
  { q: "Omnia, Aliena Sunt, Tempus Tantum Nostrum Est. All things are alien; time alone is ours.", a: "Seneca" },
  { q: "No man was ever wise by chance.", a: "Seneca" },
  { q: "The first step is the hardest — to think, to sort out, to decide.", a: "Seneca" },
  { q: "Retire into yourself as much as possible with men who will make you better.", a: "Seneca" },
  { q: "If a man knows not to which port he sails, no wind is favorable.", a: "Seneca" },
  { q: "Difficulties strengthen the mind, as labor does the body.", a: "Seneca" },
  { q: "Knowledge is power.", a: "Francis Bacon" },
  { q: "An investment in knowledge pays the best interest.", a: "Benjamin Franklin" },
  { q: "The more that you read, the more things you will know.", a: "Dr. Seuss" },
  { q: "Knowing is not enough; we must apply. Willing is not enough; we must do.", a: "Johann Wolfgang von Goethe" },
  { q: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", a: "Benjamin Franklin" },
  { q: "The beautiful thing about learning is that no one can take it away from you.", a: "B.B. King" },
  { q: "Live as if you were to die tomorrow. Learn as if you were to live forever.", a: "Mahatma Gandhi" },
  { q: "The noblest pleasure is the joy of understanding.", a: "Leonardo da Vinci" },
  { q: "The more I learn, the more I realize how much I don't know.", a: "Albert Einstein" },
  { q: "Education is not the filling of a pail, but the lighting of a fire.", a: "W.B. Yeats" },
  { q: "A mind that is stretched by a new experience can never go back to its old dimensions.", a: "Oliver Wendell Holmes" },
  { q: "Strive not to be a success, but rather to be of value.", a: "Albert Einstein" },
  { q: "Imagination is more important than knowledge.", a: "Albert Einstein" },
  { q: "Simplicity is the ultimate sophistication.", a: "Leonardo da Vinci" },
  { q: "Creativity is intelligence having fun.", a: "Albert Einstein" },
  { q: "I have not failed. I've just found 10,000 ways that won't work.", a: "Thomas Edison" },
  { q: "Genius is one percent inspiration and ninety-nine percent perspiration.", a: "Thomas Edison" },
  { q: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", a: "Thomas Edison" },
  { q: "Vision without execution is just hallucination.", a: "Thomas Edison" },
  { q: "I never did anything worth doing by accident, nor did any of my inventions come by accident.", a: "Thomas Edison" },
  { q: "The only real mistake is the one from which we learn nothing.", a: "Henry Ford" },
  { q: "Whether you think you can or you think you can't, you're right.", a: "Henry Ford" },
  { q: "Coming together is a beginning, staying together is progress, and working together is success.", a: "Henry Ford" },
  { q: "Quality means doing it right when no one is looking.", a: "Henry Ford" },
  { q: "Obstacles are those frightful things you see when you take your eyes off your goal.", a: "Henry Ford" },
  { q: "Success is not final; failure is not fatal: It is the courage to continue that counts.", a: "Winston Churchill" },
  { q: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", a: "Winston Churchill" },
  { q: "Success is stumbling from failure to failure with no loss of enthusiasm.", a: "Winston Churchill" },
  { q: "We make a living by what we get. We make a life by what we give.", a: "Winston Churchill" },
  { q: "The price of greatness is responsibility.", a: "Winston Churchill" },
  { q: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", a: "Socrates" },
  { q: "The unexamined life is not worth living.", a: "Socrates" },
  { q: "To know thyself is the beginning of wisdom.", a: "Socrates" },
  { q: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", a: "Socrates" },
  { q: "Education is the kindling of a flame, not the filling of a vessel.", a: "Socrates" },
  { q: "There is only one good, knowledge, and one evil, ignorance.", a: "Socrates" },
  { q: "Beware the barrenness of a busy life.", a: "Socrates" },
  { q: "He who is not contented with what he has, would not be contented with what he would like to have.", a: "Socrates" },
  { q: "The secret to happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.", a: "Socrates" },
  { q: "I cannot teach anybody anything. I can only make them think.", a: "Socrates" },
  { q: "Knowing yourself is the beginning of all wisdom.", a: "Aristotle" },
  { q: "Pleasure in the job puts perfection in the work.", a: "Aristotle" },
  { q: "We are what we repeatedly do. Excellence is not an act but a habit.", a: "Aristotle" },
  { q: "Patience is bitter, but its fruit is sweet.", a: "Aristotle" },
  { q: "The more you know, the more you know you don't know.", a: "Aristotle" },
  { q: "Well begun is half done.", a: "Aristotle" },
  { q: "Excellence is never an accident.", a: "Aristotle" },
  { q: "To appreciate the beauty of a snowflake it is necessary to stand out in the cold.", a: "Aristotle" },
  { q: "Happiness depends upon ourselves.", a: "Aristotle" },
  { q: "Hope is the dream of a waking man.", a: "Aristotle" },
  { q: "In order to carry a positive action we must develop here a positive vision.", a: "Dalai Lama" },
  { q: "Silence is sometimes the best answer.", a: "Dalai Lama" },
  { q: "If you think you are too small to make a difference, try sleeping with a mosquito.", a: "Dalai Lama" },
  { q: "Remember that the best relationship is one in which your love for each other exceeds your need for each other.", a: "Dalai Lama" },
  { q: "The purpose of our lives is to be happy.", a: "Dalai Lama" },
  { q: "Be the change you wish to see in the world.", a: "Mahatma Gandhi" },
  { q: "Strength does not come from physical capacity. It comes from an indomitable will.", a: "Mahatma Gandhi" },
  { q: "The best way to find yourself is to lose yourself in the service of others.", a: "Mahatma Gandhi" },
  { q: "First they ignore you, then they laugh at you, then they fight you, then you win.", a: "Mahatma Gandhi" },
  { q: "In a gentle way, you can shake the world.", a: "Mahatma Gandhi" },
  { q: "A person who never made a mistake never tried anything new.", a: "Albert Einstein" },
  { q: "Logic will get you from A to B. Imagination will take you everywhere.", a: "Albert Einstein" },
  { q: "Life is like riding a bicycle. To keep your balance, you must keep moving.", a: "Albert Einstein" },
  { q: "The measure of intelligence is the ability to change.", a: "Albert Einstein" },
  { q: "If you can't explain it simply, you don't understand it well enough.", a: "Albert Einstein" },
  { q: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", a: "Albert Einstein" },
  { q: "Try not to become a man of success, but rather try to become a man of value.", a: "Albert Einstein" },
  { q: "Great spirits have always encountered violent opposition from mediocre minds.", a: "Albert Einstein" },
  { q: "A clever person solves a problem. A wise person avoids it.", a: "Albert Einstein" },
  { q: "You never fail until you stop trying.", a: "Albert Einstein" },
  { q: "The mind is everything. What you think you become.", a: "Buddha" },
  { q: "Peace comes from within. Do not seek it without.", a: "Buddha" },
  { q: "Three things cannot be long hidden: the sun, the moon, and the truth.", a: "Buddha" },
  { q: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", a: "Buddha" },
  { q: "The root of suffering is attachment.", a: "Buddha" },
  { q: "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go.", a: "Buddha" },
  { q: "You yourself must strive. The Buddhas only point the way.", a: "Buddha" },
  { q: "No one saves us but ourselves. No one can and no one may.", a: "Buddha" },
  { q: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", a: "Buddha" },
  { q: "Your work is to discover your world and then with all your heart give yourself to it.", a: "Buddha" },
  { q: "Absorb what is useful, reject what is useless, add what is specifically your own.", a: "Bruce Lee" },
  { q: "Knowing is not enough, we must apply. Willing is not enough, we must do.", a: "Bruce Lee" },
  { q: "Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind.", a: "Bruce Lee" },
  { q: "Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it.", a: "Bruce Lee" },
  { q: "A goal is not always meant to be reached; it often serves simply as something to aim at.", a: "Bruce Lee" },
  { q: "Do not pray for an easy life, pray for the strength to endure a difficult one.", a: "Bruce Lee" },
  { q: "Real living is living for others.", a: "Bruce Lee" },
  { q: "As you think, so shall you become.", a: "Bruce Lee" },
  { q: "If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life.", a: "Bruce Lee" },
  { q: "The key to immortality is first living a life worth remembering.", a: "Bruce Lee" },
  { q: "Life is 10% what happens to you and 90% how you react to it.", a: "Charles R. Swindoll" },
  { q: "It's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { q: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", a: "Abraham Lincoln" },
  { q: "Whatever you are, be a good one.", a: "Abraham Lincoln" },
  { q: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", a: "Abraham Lincoln" },
  { q: "The best way to predict your future is to create it.", a: "Abraham Lincoln" },
  { q: "I walk slowly, but I never walk backward.", a: "Abraham Lincoln" },
  { q: "Things may come to those who wait, but only the things left by those who hustle.", a: "Abraham Lincoln" },
  { q: "You cannot escape the responsibility of tomorrow by evading it today.", a: "Abraham Lincoln" },
  { q: "In the end, it's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { q: "Creativity is connecting things.", a: "Steve Jobs" },
  { q: "Innovation distinguishes between a leader and a follower.", a: "Steve Jobs" },
  { q: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { q: "Stay hungry, stay foolish.", a: "Steve Jobs" },
  { q: "Details matter, it's worth waiting to get it right.", a: "Steve Jobs" },
  { q: "The people who are crazy enough to think they can change the world are the ones who do.", a: "Steve Jobs" },
  { q: "Simple can be harder than complex. You have to work hard to get your thinking clean to make it simple.", a: "Steve Jobs" },
];
