"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 15:59:13.679013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_segments',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.REAL(), nullable=False),
    sa.Column('productive_sec', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('rest_sec', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('preset_id', sa.Text(), nullable=True),
    sa.Column('preset_name', sa.Text(), nullable=True),
    sa.Column('phase_index', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('activity_segments', schema=None) as batch_op:
        batch_op.create_index('idx_activity_segments_day', ['day', 'started_at'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('id = 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_presets',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('work_min', sa.Integer(), nullable=False),
    sa.Column('short_rest_min', sa.Integer(), nullable=False),
    sa.Column('long_rest_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('daily_focus',
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_focus')
    op.drop_table('custom_presets')
    op.drop_table('app_settings')
    with op.batch_alter_table('activity_segments', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_segments_day')

    op.drop_table('activity_segments')
    # ### end Alembic commands ###
